=== VictorRodBon/Acceso-a-datos/ra2/ad-ra2-actividad1/src/main/resources/xsd/aeropuertos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definición del elemento raíz que contendrá múltiples aeropuertos -->
    <xs:element name="aeropuertos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="aeropuerto" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="aeropuerto">
        <xs:complexType>
            <xs:sequence>
                <!-- Referencia a un tipo simple personalizado para el IATA -->
                <xs:element name="iata" type="tipoIATA"/>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="ciudad" type="xs:string"/>
                <xs:element name="pais" type="xs:string"/>
                <!-- La tasa debe ser un número entero positivo -->
                <xs:element name="tasa" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Restricción personalizada: El IATA deben ser exactamente 3 letras mayúsculas -->
    <xs:simpleType name="tipoIATA">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== VictorRodBon/Acceso-a-datos/ra2/ad-ra2-actividad1 (Copia 1)/ad-ra2-actividad1/src/main/resources/xml/aeropuertos.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuertos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../xsd/aeropuertos.xsd">
    <aeropuerto>
        <iata>AGP</iata>
        <nombre>Costa del Sol</nombre>
        <ciudad>Málaga</ciudad>
        <pais>España</pais>
        <tasa>1200</tasa>
    </aeropuerto>
    <aeropuerto>
        <iata>VLC</iata>
        <nombre>Manises</nombre>
        <ciudad>Valencia</ciudad>
        <pais>España</pais>
        <tasa>980</tasa>
    </aeropuerto>
    <aeropuerto>
        <iata>LIS</iata>
        <nombre>Humberto Delgado</nombre>
        <ciudad>Lisboa</ciudad>
        <pais>Portugal</pais>
        <tasa>1300</tasa>
    </aeropuerto>
    <aeropuerto>
        <iata>AMS</iata>
        <nombre>Schiphol</nombre>
        <ciudad>Ámsterdam</ciudad>
        <pais>Países Bajos</pais>
        <tasa>1600</tasa>
    </aeropuerto>
    <aeropuerto>
        <iata>FRA</iata>
        <nombre>Frankfurt am Main</nombre>
        <ciudad>Fráncfort</ciudad>
        <pais>Alemania</pais>
        <tasa>2200</tasa>
    </aeropuerto>
</aeropuertos>
